# Generated by Django 4.2.1 on 2023-05-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=100, verbose_name='Markė')),
                ('modelis', models.CharField(max_length=100, verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Automobilio modelis',
                'verbose_name_plural': 'Automobilių modeliai',
            },
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(max_length=100, verbose_name='valstybinis nr')),
                ('vin_kodas', models.CharField(max_length=100, verbose_name='VIN kodas')),
                ('klientas', models.CharField(max_length=100, verbose_name='Klientas')),
                ('automobilio_modelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Automobiliai', to='car_service.automobiliomodelis', verbose_name='Automobilio modelis')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('kaina', models.IntegerField(verbose_name='Kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField(verbose_name='Data')),
                ('suma', models.IntegerField(verbose_name='Suma')),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzsakymai', to='car_service.automobilis', verbose_name='Uzsakymas')),
            ],
            options={
                'verbose_name': 'Uzsakymas',
                'verbose_name_plural': 'Uzsakymai',
            },
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(verbose_name='Kiekis')),
                ('kaina', models.IntegerField(verbose_name='Kaina')),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzsakymu_eilutes', to='car_service.paslauga', verbose_name='uzsakumo eilute')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzsakymu_eilutes', to='car_service.uzsakymas', verbose_name='uzsakumo eilute')),
            ],
            options={
                'verbose_name': 'Uzsakymo eilute',
                'verbose_name_plural': 'Uzsakymu eilutes',
            },
        ),
    ]
